export const SEND_INVITES_ATTEMPT: string = 'SEND_INVITES_ATTEMPT';
export const SEND_INVITES_FULFILLED: string = 'SEND_INVITES_FULFILLED';
export const SEND_INVITES_FAILED: string = 'SEND_INVITES_FAILED';